//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickPoint
    {
        public int Id { get; set; }
        public int PIndex { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
        public int HouseNumber { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
